{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.20/report-generator-1.0.20.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.20.jar",
          "url": "report-generator-jvm-1.0.20.jar",
          "size": 279483,
          "sha512": "367ae9d4a20035505f9244fe5fdf6d9d1d231bd104d8766c20cfc5748a16be20c032d010d4b2b86bf9fade2c9fea5bacbf79f45b7e8e43fe262eddcee6d5cb65",
          "sha256": "ce87be945bbdcc33d2bb515e43c57238a91b7c374211e7ad6e73de9fffa98fd2",
          "sha1": "e4b7e8c425291ce6ea7c617529afbc7492247db3",
          "md5": "8b387867e920a7082c7047e818e7a430"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        },
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.20.jar",
          "url": "report-generator-jvm-1.0.20.jar",
          "size": 279483,
          "sha512": "367ae9d4a20035505f9244fe5fdf6d9d1d231bd104d8766c20cfc5748a16be20c032d010d4b2b86bf9fade2c9fea5bacbf79f45b7e8e43fe262eddcee6d5cb65",
          "sha256": "ce87be945bbdcc33d2bb515e43c57238a91b7c374211e7ad6e73de9fffa98fd2",
          "sha1": "e4b7e8c425291ce6ea7c617529afbc7492247db3",
          "md5": "8b387867e920a7082c7047e818e7a430"
        }
      ]
    }
  ]
}
