{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.17/report-generator-1.0.17.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator.klib",
          "url": "report-generator-native-1.0.17.klib",
          "size": 86193,
          "sha512": "fb6ff2d663d47f3bbb172629956eed9c5b952d8415fc5ec373a1093460420a7c7dbc5c468deb720f805d9b2c39cf927b7116e0f064153d00e2594b2df4db2c41",
          "sha256": "13bf351b0e844578c437e2ae503d1420bb23ef1377b3fcb1dc391db4a8ba958b",
          "sha1": "13980f0c88873da774d357971a91db2d7a58f481",
          "md5": "125b0dc3166107fb432af652505299b9"
        }
      ]
    },
    {
      "name": "nativeMetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-native-1.0.17-metadata.jar",
          "url": "report-generator-native-1.0.17-metadata.jar",
          "size": 261,
          "sha512": "77634b1531bac73fab00e7bf063384e14bfd3385a68d711d272958542bfb414502c16c39b6b2bfc0089c68bd0de36f1e02c7706dc9373e966a8231f5177a7e15",
          "sha256": "62a5915490acbcd67b1b0562965f8bb88f1388a52d0e6e76c7099f8eb7f62774",
          "sha1": "ea740aaf550016d3848b2cb50f4a16ed9859dcfe",
          "md5": "4bee95fdab552823aaa0513b1f1d23f5"
        }
      ]
    }
  ]
}
