{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-metadata-1.0.17-all.jar",
          "url": "report-generator-1.0.17-all.jar",
          "size": 13716,
          "sha512": "9eed5689b847167cefbdd4a798832deb398f77598118c51a0f864db242411238e955a727b66c4945db48b5cd414958dec84734124e7d18ee98f89f95dfde73e1",
          "sha256": "d0c18b93a3b4aa39fbadd4cab5db333f1cb9e48080bc943c23fca9042584cd80",
          "sha1": "5f417919214a25852119a503a9dd4c6a6e038174",
          "md5": "6bb6eb3a72d6316d0bd9d0f18b000933"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-1.0.17.jar",
          "url": "report-generator-1.0.17.jar",
          "size": 36273,
          "sha512": "0ce7b36b6780301992f9f7b119cc12b38b6e5a155bf6ba116a87bbb6c5647a02240c083ad85428b10b17ba9ea12388eff4905ac6207eb04c8c1014caabab9567",
          "sha256": "b3fe0e403133fc40508d0b571bb4916b9fd073806b3688cbc7d201de8af44eac",
          "sha1": "58d72c9df8cf9930f8e4116f096576e43e5fe618",
          "md5": "30e5d5dc2ec59a68fb7b33a3a253ee04"
        }
      ]
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../report-generator-js/1.0.17/report-generator-js-1.0.17.module",
        "group": "com.iprd.report",
        "module": "report-generator-js",
        "version": "1.0.17"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../report-generator-js/1.0.17/report-generator-js-1.0.17.module",
        "group": "com.iprd.report",
        "module": "report-generator-js",
        "version": "1.0.17"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../report-generator-js/1.0.17/report-generator-js-1.0.17.module",
        "group": "com.iprd.report",
        "module": "report-generator-js",
        "version": "1.0.17"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../report-generator-js/1.0.17/report-generator-js-1.0.17.module",
        "group": "com.iprd.report",
        "module": "report-generator-js",
        "version": "1.0.17"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../report-generator-jvm/1.0.17/report-generator-jvm-1.0.17.module",
        "group": "com.iprd.report",
        "module": "report-generator-jvm",
        "version": "1.0.17"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../report-generator-jvm/1.0.17/report-generator-jvm-1.0.17.module",
        "group": "com.iprd.report",
        "module": "report-generator-jvm",
        "version": "1.0.17"
      }
    },
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../report-generator-native/1.0.17/report-generator-native-1.0.17.module",
        "group": "com.iprd.report",
        "module": "report-generator-native",
        "version": "1.0.17"
      }
    },
    {
      "name": "nativeMetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../report-generator-native/1.0.17/report-generator-native-1.0.17.module",
        "group": "com.iprd.report",
        "module": "report-generator-native",
        "version": "1.0.17"
      }
    }
  ]
}
