{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.24/report-generator-1.0.24.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.24.jar",
          "url": "report-generator-jvm-1.0.24.jar",
          "size": 281380,
          "sha512": "fa78fd36f664fd600574e58d94ac53f4e01c10c2c14a180a8a30e8186268ab75c719dff858d5b7ae11572e69077f6d641f886660a27c4aa99255e8f16ecb8547",
          "sha256": "e374b7cd2829773ef419b85848c208c8454ad8acedf3334e3d79bb74e01d7e4b",
          "sha1": "bfaf3f90c0343104794b268056070b39c12bd2ec",
          "md5": "805454ed685ab89ff361220a30c8421d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        },
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.24.jar",
          "url": "report-generator-jvm-1.0.24.jar",
          "size": 281380,
          "sha512": "fa78fd36f664fd600574e58d94ac53f4e01c10c2c14a180a8a30e8186268ab75c719dff858d5b7ae11572e69077f6d641f886660a27c4aa99255e8f16ecb8547",
          "sha256": "e374b7cd2829773ef419b85848c208c8454ad8acedf3334e3d79bb74e01d7e4b",
          "sha1": "bfaf3f90c0343104794b268056070b39c12bd2ec",
          "md5": "805454ed685ab89ff361220a30c8421d"
        }
      ]
    }
  ]
}
