{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.38/report-generator-1.0.38.module",
    "group": "org.opencampaignlink",
    "module": "report-generator",
    "version": "1.0.38",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "itext7-core",
              "type": "pom",
              "extension": "pom"
            }
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.38.jar",
          "url": "report-generator-jvm-1.0.38.jar",
          "size": 339323,
          "sha512": "966e0b255b8147289877ae7900386109b6fec96de38377d1e0e18d6cfecbd38905c87fc6292a749aa887b8abe619214fe31a712ba87a85bda0bcb99e9358bc34",
          "sha256": "795249969c143e560bec44ffdbbc3320a59aacacc1f909efdb2e1b8cbfc86d85",
          "sha1": "426cfbd73dac3030912f33d9cf2a97a8e663a597",
          "md5": "206c42e1f65bd8cfcb8e6dd79c9105cc"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "itext7-core",
              "type": "pom",
              "extension": "pom"
            }
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        },
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.38.jar",
          "url": "report-generator-jvm-1.0.38.jar",
          "size": 339323,
          "sha512": "966e0b255b8147289877ae7900386109b6fec96de38377d1e0e18d6cfecbd38905c87fc6292a749aa887b8abe619214fe31a712ba87a85bda0bcb99e9358bc34",
          "sha256": "795249969c143e560bec44ffdbbc3320a59aacacc1f909efdb2e1b8cbfc86d85",
          "sha1": "426cfbd73dac3030912f33d9cf2a97a8e663a597",
          "md5": "206c42e1f65bd8cfcb8e6dd79c9105cc"
        }
      ]
    }
  ]
}
