{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.17/report-generator-1.0.17.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jslegacy-1.0.17.jar",
          "url": "report-generator-js-1.0.17.jar",
          "size": 33628,
          "sha512": "8f7ab0bb49f846ece5c850297217bc6bf3061f06e93c71633915aba295ea0decc93aec33ab6111e86f4f95f0605691c511c52bbe654b80019fd07f65eaddb579",
          "sha256": "37632ad49f6d3ce7276e1829d3c981be9add62eabdd6c46c1fcc0f8c694bc5ca",
          "sha1": "cc1d3c3c52602494d05e149bc2fa082150c753d5",
          "md5": "6283802d0fb4e9f98e1f9d0dd43988c8"
        }
      ]
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jslegacy-1.0.17.jar",
          "url": "report-generator-js-1.0.17.jar",
          "size": 33628,
          "sha512": "8f7ab0bb49f846ece5c850297217bc6bf3061f06e93c71633915aba295ea0decc93aec33ab6111e86f4f95f0605691c511c52bbe654b80019fd07f65eaddb579",
          "sha256": "37632ad49f6d3ce7276e1829d3c981be9add62eabdd6c46c1fcc0f8c694bc5ca",
          "sha1": "cc1d3c3c52602494d05e149bc2fa082150c753d5",
          "md5": "6283802d0fb4e9f98e1f9d0dd43988c8"
        }
      ]
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jsir-1.0.17.klib",
          "url": "report-generator-js-1.0.17.klib",
          "size": 94722,
          "sha512": "fb4c12f913b5f38276c2fe39b72767f5d1a94dff0744c26db41464f7bfd278753a8b4ef964771a6030158d6d7e82ed2ccbd04acfba2b146988f7523948164e89",
          "sha256": "09484df8a8541589b3586e812e0f2e4ff68930c2609c86dc3ae6201b251ea7cb",
          "sha1": "c38257add2dc56d7e15bbcb09e3333d6043d184b",
          "md5": "78c22e2d2ff38df2d9d02f792ccfe75e"
        }
      ]
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jsir-1.0.17.klib",
          "url": "report-generator-js-1.0.17.klib",
          "size": 94722,
          "sha512": "fb4c12f913b5f38276c2fe39b72767f5d1a94dff0744c26db41464f7bfd278753a8b4ef964771a6030158d6d7e82ed2ccbd04acfba2b146988f7523948164e89",
          "sha256": "09484df8a8541589b3586e812e0f2e4ff68930c2609c86dc3ae6201b251ea7cb",
          "sha1": "c38257add2dc56d7e15bbcb09e3333d6043d184b",
          "md5": "78c22e2d2ff38df2d9d02f792ccfe75e"
        }
      ]
    }
  ]
}
