{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.25/report-generator-1.0.25.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.25.jar",
          "url": "report-generator-jvm-1.0.25.jar",
          "size": 280668,
          "sha512": "6925dde122f622c76a89f2e85632ffa834da5bf9adceb60794720ed8a1e5c403cbfd27c246677b8a148ecb2cffa7d4350ec063e5d605e3110130f52748942d9f",
          "sha256": "acd1089dcca3ad6500d02c38abe0f7c35b85dba57070fb90d7183f79b1acd5a7",
          "sha1": "5709456bf3d3ab9749eddca504d2f15c38be0726",
          "md5": "2e1de73c32cee9e9fbda3cf184ecb422"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        },
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.25.jar",
          "url": "report-generator-jvm-1.0.25.jar",
          "size": 280668,
          "sha512": "6925dde122f622c76a89f2e85632ffa834da5bf9adceb60794720ed8a1e5c403cbfd27c246677b8a148ecb2cffa7d4350ec063e5d605e3110130f52748942d9f",
          "sha256": "acd1089dcca3ad6500d02c38abe0f7c35b85dba57070fb90d7183f79b1acd5a7",
          "sha1": "5709456bf3d3ab9749eddca504d2f15c38be0726",
          "md5": "2e1de73c32cee9e9fbda3cf184ecb422"
        }
      ]
    }
  ]
}
