{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.19/report-generator-1.0.19.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.19.jar",
          "url": "report-generator-jvm-1.0.19.jar",
          "size": 319375,
          "sha512": "c3d9271e552907b239dc714a7dffe117b5caca9fb1180973ba0dc903481eaad0b118472fde833ffcf17b5bd1b5f3d7d166dd8aa15a80fdbd74e32afed23a563c",
          "sha256": "bf2b109ededda4d83adb942062c1e9707d05abbef8618891491ee8f82234570a",
          "sha1": "516c332f0b7976065f28922f4c0722a94e422040",
          "md5": "ea40999e14964db179301e8adf98b821"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        },
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.19.jar",
          "url": "report-generator-jvm-1.0.19.jar",
          "size": 319375,
          "sha512": "c3d9271e552907b239dc714a7dffe117b5caca9fb1180973ba0dc903481eaad0b118472fde833ffcf17b5bd1b5f3d7d166dd8aa15a80fdbd74e32afed23a563c",
          "sha256": "bf2b109ededda4d83adb942062c1e9707d05abbef8618891491ee8f82234570a",
          "sha1": "516c332f0b7976065f28922f4c0722a94e422040",
          "md5": "ea40999e14964db179301e8adf98b821"
        }
      ]
    }
  ]
}
