{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.19/report-generator-1.0.19.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.19.jar",
          "url": "report-generator-jvm-1.0.19.jar",
          "size": 319054,
          "sha512": "9523eef29cbaaa391137d2c52f9dd39dae58ef17f3991d54183cc0d276a459b452383436e3bd14a3e09da18981d6b82536712849bb2d5cd8764db9fac45fa632",
          "sha256": "a40d4f2ccfe9b13306fdbf294e0febea264e41fa4b5c44eb5f0fe8957f5da17c",
          "sha1": "11ae41656034db8517ed3dcf9d5b91465f54c5b1",
          "md5": "589195b2be613fd39fbc10b9522c4399"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        },
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.19.jar",
          "url": "report-generator-jvm-1.0.19.jar",
          "size": 319054,
          "sha512": "9523eef29cbaaa391137d2c52f9dd39dae58ef17f3991d54183cc0d276a459b452383436e3bd14a3e09da18981d6b82536712849bb2d5cd8764db9fac45fa632",
          "sha256": "a40d4f2ccfe9b13306fdbf294e0febea264e41fa4b5c44eb5f0fe8957f5da17c",
          "sha1": "11ae41656034db8517ed3dcf9d5b91465f54c5b1",
          "md5": "589195b2be613fd39fbc10b9522c4399"
        }
      ]
    }
  ]
}
