{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.19/report-generator-1.0.19.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.19.jar",
          "url": "report-generator-jvm-1.0.19.jar",
          "size": 319363,
          "sha512": "9effa3ed96ae44c2a2bdbf714e873723fc1f05c25606886a246a0831a01ada645bf5990100b9fc04502404790892dd1beba35f90cf926c6d7d6b975ce453ad3f",
          "sha256": "bd6b98b907b00dba64b3f027dc047c3173a7d1ee58d738bb2c57c33c65ffb494",
          "sha1": "add3acbaa9a3fa4ecc3ee6a3f305743d89869e13",
          "md5": "2aefbfe9aa10c7f118f140702820027b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        },
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.19.jar",
          "url": "report-generator-jvm-1.0.19.jar",
          "size": 319363,
          "sha512": "9effa3ed96ae44c2a2bdbf714e873723fc1f05c25606886a246a0831a01ada645bf5990100b9fc04502404790892dd1beba35f90cf926c6d7d6b975ce453ad3f",
          "sha256": "bd6b98b907b00dba64b3f027dc047c3173a7d1ee58d738bb2c57c33c65ffb494",
          "sha1": "add3acbaa9a3fa4ecc3ee6a3f305743d89869e13",
          "md5": "2aefbfe9aa10c7f118f140702820027b"
        }
      ]
    }
  ]
}
