{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.29/report-generator-1.0.29.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "itext7-core",
              "type": "pom",
              "extension": "pom"
            }
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.29.jar",
          "url": "report-generator-jvm-1.0.29.jar",
          "size": 306180,
          "sha512": "60dc27d38114686881470731b68f2b203b4ba8102c3ccde45b3438b599982809ca6839f6aa523e432a2fd72f80c0b99db7922c0565dc0e214fc9c6d3bbb65b0d",
          "sha256": "11fca87d926644d9db66523d5937ae62acb533950769d1b777f19236fc16ce40",
          "sha1": "4a3d2563c714f90cd68062a38892d195efe3596c",
          "md5": "6d6b318a149218ce3200fb2428917c3e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "itext7-core",
              "type": "pom",
              "extension": "pom"
            }
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        },
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.29.jar",
          "url": "report-generator-jvm-1.0.29.jar",
          "size": 306180,
          "sha512": "60dc27d38114686881470731b68f2b203b4ba8102c3ccde45b3438b599982809ca6839f6aa523e432a2fd72f80c0b99db7922c0565dc0e214fc9c6d3bbb65b0d",
          "sha256": "11fca87d926644d9db66523d5937ae62acb533950769d1b777f19236fc16ce40",
          "sha1": "4a3d2563c714f90cd68062a38892d195efe3596c",
          "md5": "6d6b318a149218ce3200fb2428917c3e"
        }
      ]
    }
  ]
}
